// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYmhlCzxF_rUuGEtn8kC6tZyWa4kv4YZ8',
    appId: '1:797125567564:web:df0adbded2f37e784f00e9',
    messagingSenderId: '797125567564',
    projectId: 'simpleecommerceapp-bcb89',
    authDomain: 'simpleecommerceapp-bcb89.firebaseapp.com',
    storageBucket: 'simpleecommerceapp-bcb89.firebasestorage.app',
    measurementId: 'G-DY733TVRE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD21mXkRHe9Ed7mYRj8NbddqN9haHttQV8',
    appId: '1:797125567564:android:f4e84f7f5a17285d4f00e9',
    messagingSenderId: '797125567564',
    projectId: 'simpleecommerceapp-bcb89',
    storageBucket: 'simpleecommerceapp-bcb89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG2Ie4HqXxEuxFbiQd27YhusxmOi1V4AI',
    appId: '1:797125567564:ios:6749c8ee1f8d3f484f00e9',
    messagingSenderId: '797125567564',
    projectId: 'simpleecommerceapp-bcb89',
    storageBucket: 'simpleecommerceapp-bcb89.firebasestorage.app',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG2Ie4HqXxEuxFbiQd27YhusxmOi1V4AI',
    appId: '1:797125567564:ios:6749c8ee1f8d3f484f00e9',
    messagingSenderId: '797125567564',
    projectId: 'simpleecommerceapp-bcb89',
    storageBucket: 'simpleecommerceapp-bcb89.firebasestorage.app',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYmhlCzxF_rUuGEtn8kC6tZyWa4kv4YZ8',
    appId: '1:797125567564:web:14d03841d7c1eadb4f00e9',
    messagingSenderId: '797125567564',
    projectId: 'simpleecommerceapp-bcb89',
    authDomain: 'simpleecommerceapp-bcb89.firebaseapp.com',
    storageBucket: 'simpleecommerceapp-bcb89.firebasestorage.app',
    measurementId: 'G-8D2K5H8NK3',
  );
}
